linters:
  rubocop:
    display_cop_names: true
files:
  ignore:
    - "bin/*"
    - "db/*"
    - "config/*"
    - "Guardfile"
    - "Rakefile"
    - "app/controllers/*"
    - 'spec/*'
    - 'app/models/*'
    - 'app/helpers/app*'